---
# WebGIS information
webgis:
  portal_url:
  username:
  password:
  # If the profile field is used - portal_url, username, and passwords fields are ignored
  profile:
  portal_item:
  layer_num:

#Agency Information
agency:
  name:
  phone:
  url:
  email:
  smtp_password:
  smtp_server:
  smtp_port:

# Google Apps Script API
gs_pdf_api:

# Local timezone
# Examples: US/Eastern, US/Central, US/Mountain, US/Pacific
local_tz:
...
